### ISSUE TITLE
Show delete option in top bar after selecting a note

### ISSUE THREAD

**Issue by Fmoment1** [PhilKes/NotallyX#105]
**Describe the solution you'd like**
Currently, if you want to delete a single note, you have to press-and-hold the note, select the three dots icon on the top right and then select delete from the drop down menu. That's three steps just to delete one note.

However, if you select two or more notes, then the delete option automatically shows up at the top bar, reducing a step compared to single note deletion.

Hence, the delete option should be at the top after selecting any note.

**Comment by PhilKes** [comment]
I implicetely implemented that already in https://github.com/PhilKes/NotallyX/pull/94/files, since I found it annoying too.
If you select a note now there is the Pin, Label and Delete Buttons visible:

![notallyx_issues_105](https://github.com/user-attachments/assets/e8bf36a8-7da8-4f12-8fca-29095e873048)
