### ISSUE TITLE
Actions like pin/label/archive only work from overview, not individual note/list

### ISSUE THREAD

**Issue by maxstarkenburg** [PhilKes/NotallyX#124]
### What happened?

When I'm on an individual note or list, if I try to pin it, archive it, or label it from there, none of those actions seem to work. The label might temporarily appear, but doesn't seem to "stick" once going back to the overview.

All these actions seem to work fine if I select the note/list from the overview page and perform it from there.

### App Version

v6.1.1

### Android Version

14

**Comment by PhilKes** [comment]
That bug is most surely introduced by [#88](https://github.com/PhilKes/NotallyX/pull/88/files#diff-225d5b56cce5c629c15cd4134aa0d35ccb25379db56cc70231edf0a3539485feR74) which saves the note only if there is a change that can be undone in the `ChangeHistory`. I will rework this, so that it saves the note if any field of `BaseNote` differs from the note when it was initially opened, which then also included `pinned`, `labels`, etc.

**Comment by maxstarkenburg** [comment]
Thank you, got the latest version and indeed this all seems fixed. Thanks for such great responsiveness!
