### ISSUE TITLE
Undo in list can be quite destructive

### ISSUE THREAD

**Issue by maxstarkenburg** [PhilKes/NotallyX#125]
### What happened?

When I use the undo feature while editing a list (namely its text contents), it typically undoes everything I've typed and shoots me back out to the overview page, undoing all my recent changes (instead of something more granular) without a chance to redo them.

If my edits are instead to delete an item, to reorder or, or to check/uncheck it, undo seems to handle those fine.

Occasionally I can get it into states where undo will either remove recently entered text letter by letter (even though my keyboard app has entered these as full words, and even though undoing in a note will undo the entire word if entered that way), and/or seems to freeze the app (prompting me to close the app or go to its info page). But I can't figure out to reliably reproduce this (except that the freezing usually, though not always, happens when I click undo "too many" times).

### App Version

v6.1.1

### Android Version

14

**Comment by PhilKes** [comment]
I had a quick look at it and indeed there is bug which can crash the app (which leads to you seeing the overview page again), because when undo/redo is triggered the cursor position is also set but there is a bug which then throws an Exception, crashing the app.
I will look into it right-away.

Just to clarify the expected behaviour is that undo/redo will always re-add/remove the characters from the last text change, meaning if you type character-by-character it will re-add/remove the last character, if you e.g. paste a text or use your keyboards word-completion and then hit undo you should see text exactly as it was before you hit paste/word-completion.

**Comment by maxstarkenburg** [comment]
Wow, thanks for such a quick response and fix! I got the latest version and was able to verify that undo seems to be behaving much better in lists now!
