### ISSUE TITLE
Bottom navigation to increase accessibility for one handed usage

### ISSUE THREAD

**Issue by Fmoment1** [PhilKes/NotallyX#129]
**Describe the solution you'd like**
Inside a note, the following buttons are available at the top bar: "pin", "undo", "redo" and "more options" (right side) and a back button (left side).

What I'm proposing is a bottom bar inside the note that would have "pin", "undo", "redo" and some features from "more options", such as "delete", "archive" and "labels" (ideally customizable, so we'd choose which options we'd like to keep in the bottom bar). This would also include the back button.

**Additional context**
This would be a huge QoL improvement for one handed usage. Letting users customize the position of the buttons would be great too.

**Comment by PhilKes** [comment]
I am also a fan of the bottom bar in Google Keep:

It includes undo/redo, text formatting, adding audio recording/images, everything you need when actually writing a note.

<img src="https://github.com/user-attachments/assets/decf30fd-f68f-430f-b9d4-c5ec81785fa2" width="300" />

<img src="https://github.com/user-attachments/assets/fd30d76e-910d-481f-b65a-56c8dc9dd7cd" width="300" />

Not sure if we would add the text formatting options here again too since they are already in the popup menu when you select text, but tbh I find Google Keeps approach more elegant, so that the user can always see the text formatting options without having to select some text first.

When clicking on `...` we could show Pin, Archive, Delete, etc. just like in the top action menu.

I'm not a huge fan of having another back button, since you can simply use the android back button or swipe gesture already on top of the back button in the top left, so adding a 3rd back button adds no benefit IMHO.

Customization would be a lot of effort, and I think there arent really enough actions to justify that, so far a first implementation I would skip customization. We can still add that later if needed
