### ISSUE TITLE
Let user choose whether add items in a todo-list at the bottom or top of already existing items

### ISSUE THREAD

**Issue by stephan75** [PhilKes/NotallyX#132]
Sometimes I have todo checkbox lists with 15 or 20 items.
When adding a new item, its is always added to the bottom of the already existing items.
Often I want to have the most recently added  item to be placed at the **top** of the item list.

The most easiest way to get this featute can be:
add another "Add Item" button placed at the TOP of the checkbox list.
When this button is pressed, add the new item at the top,
same way add to the bottom end of the list when the so far already existing "Add Item" button is pressed.

Would this be possible?

**Comment by PhilKes** [comment]
I am not sure if adding the same button, but on top is the best solution, since this can be quite annoying for people that never use it, it just takes up space. Usually when I create lists I dont really mind that a new item is placed on the bottom.

But maybe I have another solution, currently if your cursor is in the 1st item and you press the IME Button, a new Item is added on the top:

[notallyx_issues_132.webm](https://github.com/user-attachments/assets/d43bb8ff-e244-4727-9bd9-f6fa172955f6)

**Comment by stephan75** [comment]
> ...
> But maybe I have another solution, currently if your cursor is in the 1st item and you press the IME/Enter Button, a new Item is added on the top:

Oh nice, that looks like a good solution!
