### ISSUE TITLE
Replace positions of "Link Note" and "Select all"

### ISSUE THREAD

**Issue by Fmoment1** [PhilKes/NotallyX#136]
**Describe the solution you'd like**
![IMG_5421080](https://github.com/user-attachments/assets/ea582405-8ded-43aa-8b46-5b243cdae3cc)

**Additional context**
Perhaps this leans too much into the domain of personal preference but I'm always used to having "select all" immediately above my finger upon opening that menu. This is really messing with my muscle memory, lol.

And as far as I can tell, "Link Note" doesnt even do anything? Correct me if I'm wrong.

**Comment by PhilKes** [comment]
The `Link Note` does what it says, see https://github.com/PhilKes/NotallyX/pull/81

But I agree, the default options should also be in the default order

**Comment by PhilKes** [comment]
> I know it's been a while, but I just wanted to say that I was actually using the link note incorrectly. It wasn't working for me because I kept linking notes without titles, lol. It only works for notes with titles (obviously).

Interesting, I haven't thought about notes with empty titles, perhaps in that case we could use either its id or the first 2-3 words of the note's content instead of the title? I guess the id would be a bit confusing since the user cant see it anywhere else. But for lists this might be confusing, should it be the first few words of the first list item?

**Comment by PhilKes** [comment]
See https://github.com/PhilKes/NotallyX/issues/166
