### ISSUE TITLE
App crashes when enabling biometric lock

### ISSUE THREAD

**Issue by PranshulGG** [PhilKes/NotallyX#168]
### What happened?

The app crashes immediately when trying to enable the biometric lock feature. BTW, its the best FOSS notes app I've used.

### App Version

v6.2.2

### Android Version

14 and 10

**Comment by ippocratis** [comment]
Stating the obvious but do you have a screen lock on device and got fingerprint added there?
The app uses the device credentials.

**Comment by PranshulGG** [comment]
> Stating the obvious but do you have a screen lock on device and got fingerprint added there?
> The app uses the device credentials.

Yeah, I do have a fingerprint scanner on my device.

**Comment by PhilKes** [comment]
Could you provide more info, what exactly happens when you do what. I have just tested enabling biometric lock on a Android 14 emulator and it worked just fine. The code to check whether or not the device has the capabilities of using biometric is quite complex, since it changed a lot over the android versions. You have problems for an Android 10 and another Android 14 device? Does it behave exactly the same on both?

**Comment by PranshulGG** [comment]
On Android 14, when I try to enable the biometric lock, the app crashes instantly without showing anything. On Android 10, it also crashes but displays the message "App stopped responding." This issue occurs with both physical and on-screen fingerprint sensors.

If it’s not fixable, that’s fine, as I’ll use the system app lock instead. You can go ahead and close this issue.

**Comment by PhilKes** [comment]
No no I am interested in fixing this, I am just afraid I'll need to see some logs in order to be able to fix it.
Do you know how to connect your phone to your computer and use logcat to see the logs?
If not there is also a built-in way to some exception logs, if you open the app, force the crash by enabling the biometric lock again, then restart the app after the crash and go to `Settings -> Create Github Issue (on the very bottom) -> Report an issue/bug` then it should open a browser with a prefilled github issue, there is a `(Optional) Relevant log output` field, which should be prefilled with the last exception logs, just copy that and comment it here. I am not sure if exceptions thrown by the checking-your-biometric-capabilities is included, but you can try and post those logs here, maybe that can help me find the issue.

**Comment by PranshulGG** [comment]
Logs after the crash

`12-22 19:07:49.074 30528 30528 E MessageQueue-JNI:      at com.philkes.notallyx.presentation.activity.main.fragment.SettingsFragment.V(SourceFile:24)
12-22 19:07:49.074 30528 30528 E MessageQueue-JNI:      at com.philkes.notallyx.presentation.activity.main.fragment.a.onClick(SourceFile:78)
12-22 19:07:49.075 30528 30528 E AndroidRuntime: Process: com.philkes.notallyx, PID: 30528
12-22 19:07:49.075 30528 30528 E AndroidRuntime:        at com.philkes.notallyx.presentation.activity.main.fragment.SettingsFragment.V(SourceFile:24)
12-22 19:07:49.075 30528 30528 E AndroidRuntime:        at com.philkes.notallyx.presentation.activity.main.fragment.a.onClick(SourceFile:78)
12-22 19:07:49.077  1226  3897 W ActivityTaskManager:   Force finishing activity com.philkes.notallyx/.presentation.activity.main.MainActivity
12-22 19:07:49.080  1226 30626 D AES     : ExceptionLog: notify aed, process:com.philkes.notallyx pid:30528 cause:data_app_crash
12-22 19:07:49.080  1226  3897 D PowerHalWrapper: <amsBoostResume> last:com.philkes.notallyx, next:ginlemon.flowerfree
12-22 19:07:49.082  1226  1241 E InputDispatcher: Window handle Window{c8985c3 u0 com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity} has no registered input channel
12-22 19:07:49.087  1226  1254 I PowerMonitorHookServer: app:com.philkes.notallyxexit top
12-22 19:07:49.089  2223  2274 I PowerMonitorNew: a whole scenario, scenario:com.philkes.notallyx, start-stop:2185465799-2185501129,duration:35330, current:0, currentconvert4V:0,currentWoBL:0,consumecoul:0,batterytime:0, conpower:0,avgsignal:300,avgDatatype:0
12-22 19:07:49.102   530   530 I SurfaceFlinger: screenshot (com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity#0)
12-22 19:07:49.113  1226  1349 W InputDispatcher: channel '4e159e3 com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-22 19:07:49.113  1226  1349 E InputDispatcher: channel '4e159e3 com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-22 19:07:49.120   530  2861 I BufferQueueProducer: [com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity#0](this:0x7f42ac9800,id:91958,api:1,p:30528,c:530) disconnect(P): api 1
12-22 19:07:49.120  1226  1241 V ActivityManager: Death received in com.android.server.am.ActivityManagerService$AppDeathRecipient@da87633 for thread android.os.BinderProxy@3300df0, mPid:30528,mApp:ProcessRecord{50f3915 30528:com.philkes.notallyx/u0a2351}
12-22 19:07:49.121  1226  1357 I WindowManager: WIN DEATH: Window{4e159e3 u0 com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity}
12-22 19:07:49.121  1226  1357 W InputDispatcher: Attempted to unregister already unregistered input channel '4e159e3 com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity (server)'
12-22 19:07:49.121  1226  1241 I ActivityManager: Process com.philkes.notallyx (pid 30528) has died: vis+99 TOP
12-22 19:07:49.122  1226  1241 D Griffin/ComponentManager: Limit Start proc com.philkes.notallyx restart for 3rd-normal
12-22 19:07:49.122  1226  2306 I WindowManager: WIN DEATH: Window{c8985c3 u0 com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity EXITING}
12-22 19:07:49.122  1226  1241 D os.ActivityManagerServiceLice: make process inactive com.philkes.notallyx(30528)
12-22 19:07:49.130  1226  1603 I ActivityManager: Applaunch form com.philkes.notallyx to ginlemon.flowerfree
12-22 19:07:49.130  1226  1241 D PowerHalWrapper: amsBoostNotify pid:28619,activity:ginlemon.flower.HomeScreen, package:ginlemon.flowerfree, mProcessCreatePackcom.philkes.notallyx
12-22 19:07:49.132   517   556 I powerd  : [powerd_req] POWER_MSG_NOTIFY_STATE, pc:0, com.philkes.notallyx => ginlemon.flowerfree
12-22 19:07:49.134   530   530 I BufferQueue: [com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity#0](this:0x7f42ac9800,id:91958,api:1,p:-1,c:-1) ~BufferQueueCore
12-22 19:07:49.250   530   530 I BufferQueue: [com.philkes.notallyx/com.philkes.notallyx.presentation.activity.main.MainActivity#1](this:0x7e9fd0c800,id:91959,api:1,p:-1,c:-1) ~BufferQueueCore
12-22 19:07:49.578  1226  1245 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{81cff2 u0 com.philkes.notallyx/.presentation.activity.main.MainActivity t-1 f}
`

**Comment by PranshulGG** [comment]
I noticed that you are using
BiometricManager.Authenticators.BIOMETRIC_STRONG and BiometricManager.Authenticators.DEVICE_CREDENTIAL for Android API 30 (Android 11), which will likely cause a crash on older versions.

Additionally, you are using BiometricPrompt.Builder, which was deprecated in API 29 (Android 10).

Edit: After reinstalling the app from GitHub on an Android 14 device, it is working fine, but you might want to check its compatibility with Android 10.

**Comment by PhilKes** [comment]
> I noticed that you are using `BiometricManager.Authenticators.BIOMETRIC_STRONG` and `BiometricManager.Authenticators.DEVICE_CREDENTIAL` for Android API 30 (Android 11), which will likely cause a crash on older versions.
> 
> Additionally, you are using `BiometricPrompt.Builder`, which was deprecated in API 29 (Android 10).
> 
> Edit: After reinstalling the app from GitHub on my Android 14 device, it is working fine, but you might want to check its compatibility with Android 10.

`BIOMETRIC_STRONG` and `DEVICE_CREDENTIAL` is only used for Android API >= 30 (`R`), so that should be fine:

https://github.com/PhilKes/NotallyX/blob/051bb4baec31d1d510d78cc99f86951e67fc8951/app/src/main/java/com/philkes/notallyx/utils/security/LockUtils.kt#L80-L85

It doesnt show me `BiometricPrompt.Builder` as deprecated, only the method [BiometricPrompt.Builder.setDeviceCredentialAllowed](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt.Builder#setDeviceCredentialAllowed%28boolean%29) seems to be deprecated in API 30, but I am not using it.

Happy to hear that a reinstall worked, although its definetely possible that there is some edge-case where the code fails. 
The app supports API 21 to 34, and it seems to me that the whole Biometric/PIN features are the ones that changed the most, unfortunately I cant test every Android version in full.

But to improve the possibility of reporting crashes like this, I added a crash activity in https://github.com/PhilKes/NotallyX/pull/171. If a crash like yours happen it should give you the opportunity to directly create a bug report on Github with the related logs. I hope this makes it easier for future crashes to be reported.

**Comment by PranshulGG** [comment]
@PhilKes, can I work on this issue? I would love to take it on!

**Comment by PhilKes** [comment]
> @PhilKes, can I work on this issue? I would love to take it on!

Sure, I am always eager for other developers to contribute 
If you need help with anything, feel free to ask for help anytime 🙂

**Comment by PranshulGG** [comment]
@PhilKes I have fixed the issue, and it is now working on Android 10. Should I go ahead and make a PR?

**Comment by PhilKes** [comment]
> @PhilKes I have fixed the issue, and it is now working on Android 10. Should I go ahead and make a PR?
> 
>  android_10.mp4

Great! Sure just open a PR :)
