### ISSUE TITLE
Import from major note apps 

### ISSUE THREAD

**Issue by ippocratis** [PhilKes/NotallyX#53]
**Describe the solution you'd like**
An option to import notes from other note apps 

**Additional context**
When switching from another note app it is hard to copy paste large amount of notes and most likely discourage users.
An option to add your notes with one click will just make it easier.

I know this is not a simple task and likely the amount of work needed to implement is not worthy .

**Comment by PhilKes** [comment]
I thought about that already too.
I already played around with Google Keeps export data, but I guess we should identify the most important note apps first.
AFAIK I would consider:
- Google Keep
- OneNote
- Evernote

Perhaps we should on the App Stores which Notes apps are the most popular ones

**Comment by ippocratis** [comment]
I think those will cover a broad userbase.
Since you can't include them all obviously due to different export methods and you don't want the list to grow large I think its fine.
Also maybe a plain text import will cover some other usecases.

**Comment by PhilKes** [comment]
@ippocratis FYI I already implemented a first version of the Google Keep Import since it is the easiest via simple JSON Files.
I also got a basic import for Evernote working, but am currently looking into correctly parsing text formatting from the ENEX files as well as extracting attached files from it (base64 encoded). But I think I will be able to create a PR for them soon.
OneNote might be trickier since Microsoft only allows to export to proprietary formats which sucks, but perhaps the `.mht` might be the way to go.
